# Generated by Django 5.2.9 on 2025-12-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablesession",
            name="bill_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tablesession",
            name="bill_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
