# Generated by Django 5.2.9 on 2025-12-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "service_charge_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
    ]
